### ISSUE TITLE
No need to wait after Wire.requestFrom() and it should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [luetzel/arduino_workshop#1]
In the file "36_bmp085_Wire/36_bmp085_Wire.ino", there are three while-loops to wait after a `Wire.requestFrom()`.
You may remove these: `while(!Wire.available());`.

In the file "35_wire_pcf8574/35_wire_pcf8574.ino", there is a `Wire.endTransmission()` after a `Wire.requestFrom()` at line 27. You may remove that line.

Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1 and 2.

**Comment by luetzel** [comment]
I missed these lines - you're right - thanks for your comment!
